############################################################################
# Contest 2026 team 498 VelaMecanum - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = velamecanum
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_498_VELAMECANUM)

MAINSRC = velamecanum_main.c

include $(APPDIR)/Application.mk